/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WaterDamageRestorationRouteImport } from './routes/water-damage-restoration'
import { Route as RoofersRouteImport } from './routes/roofers'
import { Route as RemodelersRouteImport } from './routes/remodelers'
import { Route as PlumbersRouteImport } from './routes/plumbers'
import { Route as HvacRouteImport } from './routes/hvac'
import { Route as GarageDoorRouteImport } from './routes/garage-door'
import { Route as FoundationRepairRouteImport } from './routes/foundation-repair'
import { Route as EpoxyFlooringRouteImport } from './routes/epoxy-flooring'
import { Route as Electricians2RouteImport } from './routes/electricians-2'
import { Route as ElectriciansRouteImport } from './routes/electricians'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminLeadsRouteImport } from './routes/admin.leads'

const WaterDamageRestorationRoute = WaterDamageRestorationRouteImport.update({
  id: '/water-damage-restoration',
  path: '/water-damage-restoration',
  getParentRoute: () => rootRouteImport,
} as any)
const RoofersRoute = RoofersRouteImport.update({
  id: '/roofers',
  path: '/roofers',
  getParentRoute: () => rootRouteImport,
} as any)
const RemodelersRoute = RemodelersRouteImport.update({
  id: '/remodelers',
  path: '/remodelers',
  getParentRoute: () => rootRouteImport,
} as any)
const PlumbersRoute = PlumbersRouteImport.update({
  id: '/plumbers',
  path: '/plumbers',
  getParentRoute: () => rootRouteImport,
} as any)
const HvacRoute = HvacRouteImport.update({
  id: '/hvac',
  path: '/hvac',
  getParentRoute: () => rootRouteImport,
} as any)
const GarageDoorRoute = GarageDoorRouteImport.update({
  id: '/garage-door',
  path: '/garage-door',
  getParentRoute: () => rootRouteImport,
} as any)
const FoundationRepairRoute = FoundationRepairRouteImport.update({
  id: '/foundation-repair',
  path: '/foundation-repair',
  getParentRoute: () => rootRouteImport,
} as any)
const EpoxyFlooringRoute = EpoxyFlooringRouteImport.update({
  id: '/epoxy-flooring',
  path: '/epoxy-flooring',
  getParentRoute: () => rootRouteImport,
} as any)
const Electricians2Route = Electricians2RouteImport.update({
  id: '/electricians-2',
  path: '/electricians-2',
  getParentRoute: () => rootRouteImport,
} as any)
const ElectriciansRoute = ElectriciansRouteImport.update({
  id: '/electricians',
  path: '/electricians',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLeadsRoute = AdminLeadsRouteImport.update({
  id: '/admin/leads',
  path: '/admin/leads',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/electricians': typeof ElectriciansRoute
  '/electricians-2': typeof Electricians2Route
  '/epoxy-flooring': typeof EpoxyFlooringRoute
  '/foundation-repair': typeof FoundationRepairRoute
  '/garage-door': typeof GarageDoorRoute
  '/hvac': typeof HvacRoute
  '/plumbers': typeof PlumbersRoute
  '/remodelers': typeof RemodelersRoute
  '/roofers': typeof RoofersRoute
  '/water-damage-restoration': typeof WaterDamageRestorationRoute
  '/admin/leads': typeof AdminLeadsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/electricians': typeof ElectriciansRoute
  '/electricians-2': typeof Electricians2Route
  '/epoxy-flooring': typeof EpoxyFlooringRoute
  '/foundation-repair': typeof FoundationRepairRoute
  '/garage-door': typeof GarageDoorRoute
  '/hvac': typeof HvacRoute
  '/plumbers': typeof PlumbersRoute
  '/remodelers': typeof RemodelersRoute
  '/roofers': typeof RoofersRoute
  '/water-damage-restoration': typeof WaterDamageRestorationRoute
  '/admin/leads': typeof AdminLeadsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/electricians': typeof ElectriciansRoute
  '/electricians-2': typeof Electricians2Route
  '/epoxy-flooring': typeof EpoxyFlooringRoute
  '/foundation-repair': typeof FoundationRepairRoute
  '/garage-door': typeof GarageDoorRoute
  '/hvac': typeof HvacRoute
  '/plumbers': typeof PlumbersRoute
  '/remodelers': typeof RemodelersRoute
  '/roofers': typeof RoofersRoute
  '/water-damage-restoration': typeof WaterDamageRestorationRoute
  '/admin/leads': typeof AdminLeadsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/electricians'
    | '/electricians-2'
    | '/epoxy-flooring'
    | '/foundation-repair'
    | '/garage-door'
    | '/hvac'
    | '/plumbers'
    | '/remodelers'
    | '/roofers'
    | '/water-damage-restoration'
    | '/admin/leads'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/electricians'
    | '/electricians-2'
    | '/epoxy-flooring'
    | '/foundation-repair'
    | '/garage-door'
    | '/hvac'
    | '/plumbers'
    | '/remodelers'
    | '/roofers'
    | '/water-damage-restoration'
    | '/admin/leads'
  id:
    | '__root__'
    | '/'
    | '/electricians'
    | '/electricians-2'
    | '/epoxy-flooring'
    | '/foundation-repair'
    | '/garage-door'
    | '/hvac'
    | '/plumbers'
    | '/remodelers'
    | '/roofers'
    | '/water-damage-restoration'
    | '/admin/leads'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ElectriciansRoute: typeof ElectriciansRoute
  Electricians2Route: typeof Electricians2Route
  EpoxyFlooringRoute: typeof EpoxyFlooringRoute
  FoundationRepairRoute: typeof FoundationRepairRoute
  GarageDoorRoute: typeof GarageDoorRoute
  HvacRoute: typeof HvacRoute
  PlumbersRoute: typeof PlumbersRoute
  RemodelersRoute: typeof RemodelersRoute
  RoofersRoute: typeof RoofersRoute
  WaterDamageRestorationRoute: typeof WaterDamageRestorationRoute
  AdminLeadsRoute: typeof AdminLeadsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/water-damage-restoration': {
      id: '/water-damage-restoration'
      path: '/water-damage-restoration'
      fullPath: '/water-damage-restoration'
      preLoaderRoute: typeof WaterDamageRestorationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roofers': {
      id: '/roofers'
      path: '/roofers'
      fullPath: '/roofers'
      preLoaderRoute: typeof RoofersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/remodelers': {
      id: '/remodelers'
      path: '/remodelers'
      fullPath: '/remodelers'
      preLoaderRoute: typeof RemodelersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plumbers': {
      id: '/plumbers'
      path: '/plumbers'
      fullPath: '/plumbers'
      preLoaderRoute: typeof PlumbersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hvac': {
      id: '/hvac'
      path: '/hvac'
      fullPath: '/hvac'
      preLoaderRoute: typeof HvacRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/garage-door': {
      id: '/garage-door'
      path: '/garage-door'
      fullPath: '/garage-door'
      preLoaderRoute: typeof GarageDoorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/foundation-repair': {
      id: '/foundation-repair'
      path: '/foundation-repair'
      fullPath: '/foundation-repair'
      preLoaderRoute: typeof FoundationRepairRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/epoxy-flooring': {
      id: '/epoxy-flooring'
      path: '/epoxy-flooring'
      fullPath: '/epoxy-flooring'
      preLoaderRoute: typeof EpoxyFlooringRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/electricians-2': {
      id: '/electricians-2'
      path: '/electricians-2'
      fullPath: '/electricians-2'
      preLoaderRoute: typeof Electricians2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/electricians': {
      id: '/electricians'
      path: '/electricians'
      fullPath: '/electricians'
      preLoaderRoute: typeof ElectriciansRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/leads': {
      id: '/admin/leads'
      path: '/admin/leads'
      fullPath: '/admin/leads'
      preLoaderRoute: typeof AdminLeadsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ElectriciansRoute: ElectriciansRoute,
  Electricians2Route: Electricians2Route,
  EpoxyFlooringRoute: EpoxyFlooringRoute,
  FoundationRepairRoute: FoundationRepairRoute,
  GarageDoorRoute: GarageDoorRoute,
  HvacRoute: HvacRoute,
  PlumbersRoute: PlumbersRoute,
  RemodelersRoute: RemodelersRoute,
  RoofersRoute: RoofersRoute,
  WaterDamageRestorationRoute: WaterDamageRestorationRoute,
  AdminLeadsRoute: AdminLeadsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
